; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24213.1 

	TITLE	E:\Documents\Cours\Git\Raven\Raven\goals\Goal_SayPhrase.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

END
